[meterRepoName0]
dynamicvariables = 1
meter = String
meterstyle = #RepoNameStyle#
measurename = #RepoMeasure#
w = #entryNameW#
h = #entryNameH#
x = (#offsetX# + #entryNameX#)
y = (#offsetY# + #entryH# * 0 + #spacingV# * 0 + #entryNameY#)
text = [#RepoMeasure#:Func(RepoName, 0)]

[meterRepoDate0]
dynamicvariables = 1
meter = String
meterstyle = #RepoDateStyle#
measurename = #RepoMeasure#
w = #entryDateW#
h = #entryDateH#
x = (#offsetX# + #entryDateX#)
y = (#offsetY# + #entryH# * 0 + #spacingV# * 0 + #entryDateY#)
text = [#RepoMeasure#:Func(RepoUpdatedAt, 0)]

[meterRepoCommitMessage0]
dynamicvariables = 1
meter = String
meterstyle = #RepoLCMStyle#
measurename = #RepoMeasure#
w = #entryCommitMessageW#
h = #entryCommitMessageH#
x = (#offsetX# + #entryCommitMessageX#)
y = (#offsetY# + #entryH# * 0 + #spacingV# * 0 + #entryCommitMessageY#)
text = [#RepoMeasure#:Func(RepoLastCommitMessage, 0)]

[meterRepoCommitAuthor0]
dynamicvariables = 1
meter = String
meterstyle = #RepoLCAStyle#
measurename = #RepoMeasure#
w = #entryCommitAuthorW#
h = #entryCommitAuthorH#
x = (#offsetX# + #entryCommitAuthorX#)
y = (#offsetY# + #entryH# * 0 + #spacingV# * 0 + #entryCommitAuthorY#)
text = By [#RepoMeasure#:Func(RepoLastCommitAuthor, 0)]

[meterRepoName1]
dynamicvariables = 1
meter = String
meterstyle = #RepoNameStyle#
measurename = #RepoMeasure#
w = #entryNameW#
h = #entryNameH#
x = (#offsetX# + #entryNameX#)
y = (#offsetY# + #entryH# * 1 + #spacingV# * 1 + #entryNameY#)
text = [#RepoMeasure#:Func(RepoName, 1)]

[meterRepoDate1]
dynamicvariables = 1
meter = String
meterstyle = #RepoDateStyle#
measurename = #RepoMeasure#
w = #entryDateW#
h = #entryDateH#
x = (#offsetX# + #entryDateX#)
y = (#offsetY# + #entryH# * 1 + #spacingV# * 1 + #entryDateY#)
text = [#RepoMeasure#:Func(RepoUpdatedAt, 1)]

[meterRepoCommitMessage1]
dynamicvariables = 1
meter = String
meterstyle = #RepoLCMStyle#
measurename = #RepoMeasure#
w = #entryCommitMessageW#
h = #entryCommitMessageH#
x = (#offsetX# + #entryCommitMessageX#)
y = (#offsetY# + #entryH# * 1 + #spacingV# * 1 + #entryCommitMessageY#)
text = [#RepoMeasure#:Func(RepoLastCommitMessage, 1)]

[meterRepoCommitAuthor1]
dynamicvariables = 1
meter = String
meterstyle = #RepoLCAStyle#
measurename = #RepoMeasure#
w = #entryCommitAuthorW#
h = #entryCommitAuthorH#
x = (#offsetX# + #entryCommitAuthorX#)
y = (#offsetY# + #entryH# * 1 + #spacingV# * 1 + #entryCommitAuthorY#)
text = By [#RepoMeasure#:Func(RepoLastCommitAuthor, 1)]

[meterRepoName2]
dynamicvariables = 1
meter = String
meterstyle = #RepoNameStyle#
measurename = #RepoMeasure#
w = #entryNameW#
h = #entryNameH#
x = (#offsetX# + #entryNameX#)
y = (#offsetY# + #entryH# * 2 + #spacingV# * 2 + #entryNameY#)
text = [#RepoMeasure#:Func(RepoName, 2)]

[meterRepoDate2]
dynamicvariables = 1
meter = String
meterstyle = #RepoDateStyle#
measurename = #RepoMeasure#
w = #entryDateW#
h = #entryDateH#
x = (#offsetX# + #entryDateX#)
y = (#offsetY# + #entryH# * 2 + #spacingV# * 2 + #entryDateY#)
text = [#RepoMeasure#:Func(RepoUpdatedAt, 2)]

[meterRepoCommitMessage2]
dynamicvariables = 1
meter = String
meterstyle = #RepoLCMStyle#
measurename = #RepoMeasure#
w = #entryCommitMessageW#
h = #entryCommitMessageH#
x = (#offsetX# + #entryCommitMessageX#)
y = (#offsetY# + #entryH# * 2 + #spacingV# * 2 + #entryCommitMessageY#)
text = [#RepoMeasure#:Func(RepoLastCommitMessage, 2)]

[meterRepoCommitAuthor2]
dynamicvariables = 1
meter = String
meterstyle = #RepoLCAStyle#
measurename = #RepoMeasure#
w = #entryCommitAuthorW#
h = #entryCommitAuthorH#
x = (#offsetX# + #entryCommitAuthorX#)
y = (#offsetY# + #entryH# * 2 + #spacingV# * 2 + #entryCommitAuthorY#)
text = By [#RepoMeasure#:Func(RepoLastCommitAuthor, 2)]

[meterRepoName3]
dynamicvariables = 1
meter = String
meterstyle = #RepoNameStyle#
measurename = #RepoMeasure#
w = #entryNameW#
h = #entryNameH#
x = (#offsetX# + #entryNameX#)
y = (#offsetY# + #entryH# * 3 + #spacingV# * 3 + #entryNameY#)
text = [#RepoMeasure#:Func(RepoName, 3)]

[meterRepoDate3]
dynamicvariables = 1
meter = String
meterstyle = #RepoDateStyle#
measurename = #RepoMeasure#
w = #entryDateW#
h = #entryDateH#
x = (#offsetX# + #entryDateX#)
y = (#offsetY# + #entryH# * 3 + #spacingV# * 3 + #entryDateY#)
text = [#RepoMeasure#:Func(RepoUpdatedAt, 3)]

[meterRepoCommitMessage3]
dynamicvariables = 1
meter = String
meterstyle = #RepoLCMStyle#
measurename = #RepoMeasure#
w = #entryCommitMessageW#
h = #entryCommitMessageH#
x = (#offsetX# + #entryCommitMessageX#)
y = (#offsetY# + #entryH# * 3 + #spacingV# * 3 + #entryCommitMessageY#)
text = [#RepoMeasure#:Func(RepoLastCommitMessage, 3)]

[meterRepoCommitAuthor3]
dynamicvariables = 1
meter = String
meterstyle = #RepoLCAStyle#
measurename = #RepoMeasure#
w = #entryCommitAuthorW#
h = #entryCommitAuthorH#
x = (#offsetX# + #entryCommitAuthorX#)
y = (#offsetY# + #entryH# * 3 + #spacingV# * 3 + #entryCommitAuthorY#)
text = By [#RepoMeasure#:Func(RepoLastCommitAuthor, 3)]

[meterRepoName4]
dynamicvariables = 1
meter = String
meterstyle = #RepoNameStyle#
measurename = #RepoMeasure#
w = #entryNameW#
h = #entryNameH#
x = (#offsetX# + #entryNameX#)
y = (#offsetY# + #entryH# * 4 + #spacingV# * 4 + #entryNameY#)
text = [#RepoMeasure#:Func(RepoName, 4)]

[meterRepoDate4]
dynamicvariables = 1
meter = String
meterstyle = #RepoDateStyle#
measurename = #RepoMeasure#
w = #entryDateW#
h = #entryDateH#
x = (#offsetX# + #entryDateX#)
y = (#offsetY# + #entryH# * 4 + #spacingV# * 4 + #entryDateY#)
text = [#RepoMeasure#:Func(RepoUpdatedAt, 4)]

[meterRepoCommitMessage4]
dynamicvariables = 1
meter = String
meterstyle = #RepoLCMStyle#
measurename = #RepoMeasure#
w = #entryCommitMessageW#
h = #entryCommitMessageH#
x = (#offsetX# + #entryCommitMessageX#)
y = (#offsetY# + #entryH# * 4 + #spacingV# * 4 + #entryCommitMessageY#)
text = [#RepoMeasure#:Func(RepoLastCommitMessage, 4)]

[meterRepoCommitAuthor4]
dynamicvariables = 1
meter = String
meterstyle = #RepoLCAStyle#
measurename = #RepoMeasure#
w = #entryCommitAuthorW#
h = #entryCommitAuthorH#
x = (#offsetX# + #entryCommitAuthorX#)
y = (#offsetY# + #entryH# * 4 + #spacingV# * 4 + #entryCommitAuthorY#)
text = By [#RepoMeasure#:Func(RepoLastCommitAuthor, 4)]

